### ISSUE TITLE
Cannot call `input()` in a GitHub Action because there is no user

### ISSUE THREAD

**Issue by cclauss** [rohan472000/twitter-recommender-sentiment-analysis#10]
input_user = input("Enter the username to get recommendations: ")

**Comment by rohan472000** [comment]
so better I add input directly without asking for input to user.

**Comment by cclauss** [comment]
Yes.  Start by hardcoding the `username`.  After that is working end-to-end, you can look at...

GitHub Actions `workflow_dispatch` can be used to ask a repo administrator for an input string when the Action is run on-demand...  https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually

**Comment by rohan472000** [comment]
after removing that it ran fine but commit stage is getting problem with error-403

https://github.com/rohan472000/twitter-recommender-sentiment-analysis/actions/runs/4609326687/jobs/8146310404

**Comment by cclauss** [comment]
~It will be difficult to write back to the `main` branch.~

~I would first try having the action create a pull request.  Start the Run EndBug/add-and-commit Action with `git checkout -b $(date +%Y_%m_%d_%H_%M_%S)` to create a new branch with a unique branch name and push changes to that branch.~

**Comment by rohan472000** [comment]
@cclauss github action ran successfully,  there was only read permission  for github action that i changed to read & write, it removed the error.
