### ISSUE TITLE
Secret Variables are not fetching variables

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/twitter-recommender-sentiment-analysis#2]
@cclauss @Diegomangasco @charlie8658 @rohit777anand , please see GitHub action, as it is failing when the code wants to fetch variables. Suggest any solution.

**Comment by charlie8658** [comment]
I'm also facing the same issue Rohan.

**Comment by Diegomangasco** [comment]
Sorry @rohan472000 I don't understand the problem

**Comment by rohan472000** [comment]
I have used twitter api which is personal token for authentication, so for security I stored them in github secret variables, but when I'm trying to them fetch in codes , they are not getting fetched, problem is in way of fetching those variables.

see add_tweets.py in this repo, where in first few lines I'm trying to fetch them.

**Comment by cclauss** [comment]
Did you setup your secrets as in
* https://medium.datadriveninvestor.com/accessing-github-secrets-in-python-d3e758d8089b

--- 

See #3

Given that the following is a Python syntax error, I would remove it.
```
>>> access_key = ${{ secrets.ACCESS_KEY }}
  File "<stdin>", line 1
    access_key = ${{ secrets.ACCESS_KEY }}
                 ^
SyntaxError: invalid syntax
```
https://github.com/rohan472000/twitter-recommender-sentiment-analysis/blob/main/add_tweets_1.py#LL7-L10C82

**Comment by rohan472000** [comment]
Traceback (most recent call last):
  File "recommender_function_6.py", line 2, in <module>
    from final_processing_5 import assign_df, preprocess_tweet, clf, vectorizer, data, similarity, \
  File "/home/runner/work/twitter-recommender-sentiment-analysis/twitter-recommender-sentiment-analysis/final_processing_5.py", line 7, in <module>
    from three_function_4 import assign_df
  File "/home/runner/work/twitter-recommender-sentiment-analysis/twitter-recommender-sentiment-analysis/three_function_4.py", line [8](https://github.com/rohan472000/twitter-recommender-sentiment-analysis/actions/runs/4605421598/jobs/8137434037#step:6:9), in <module>
    from add_tweets_1 import api
  File "/home/runner/work/twitter-recommender-sentiment-analysis/twitter-recommender-sentiment-analysis/add_tweets_1.py", line 7, in <module>
    access_key = os.environ['ACCESS_KEY']
  File "/opt/hostedtoolcache/Python/3.8.[16](https://github.com/rohan472000/twitter-recommender-sentiment-analysis/actions/runs/4605421598/jobs/8137434037#step:6:17)/x64/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'ACCESS_KEY'
Error: Process completed with exit code



In above error message suggests that the script is trying to access an environment variable named "ACCESS_KEY" using the "os.environ" dictionary, but that variable is not defined. But I have defined an environment named 'myenv' and kept these variables there.

**Comment by cclauss** [comment]
Please reopen the issue if it is not solved.

**Comment by cclauss** [comment]
At https://github.com/rohan472000/twitter-recommender-sentiment-analysis/settings/secrets/actions
1. Are these defined as `secrets` or `variables`?
2. Are these defined as `Environment secrets` or `Repository secrets`?

I defined as `Repository secrets` and they work for me.

**Comment by rohan472000** [comment]
I deleted my env secrets , kept only repository secrets and variables, and ran but got below 'AssertionError'

Traceback (most recent call last):
  File "recommender_function_6.py", line 2, in <module>
    from final_processing_5 import assign_df, preprocess_tweet, clf, vectorizer, data, similarity, \
  File "/home/runner/work/twitter-recommender-sentiment-analysis/twitter-recommender-sentiment-analysis/final_processing_5.py", line 7, in <module>
    from three_function_4 import assign_df
  File "/home/runner/work/twitter-recommender-sentiment-analysis/twitter-recommender-sentiment-analysis/three_function_4.py", line [8](https://github.com/rohan472000/twitter-recommender-sentiment-analysis/actions/runs/4606036936/jobs/8138838839#step:6:9), in <module>
    from add_tweets_1 import api
  File "/home/runner/work/twitter-recommender-sentiment-analysis/twitter-recommender-sentiment-analysis/add_tweets_1.py", line 17, in <module>
    assert all((access_key, access_secret, consumer_key, consumer_secret))
AssertionError

**Comment by cclauss** [comment]
Screenshot of https://github.com/rohan472000/twitter-recommender-sentiment-analysis/settings/secrets/actions please?

**Comment by rohan472000** [comment]
![image](https://user-images.githubusercontent.com/96521078/229747361-b5235f74-9b53-4516-b14d-c0507c3caa0c.png)

**Comment by rohan472000** [comment]
still that error is coming in github actions

**Comment by cclauss** [comment]
At https://github.com/rohan472000/twitter-recommender-sentiment-analysis/settings/secrets/actions these keys are present but their values are left blank.
```python
import os
print(sorted(os.environ))
KEYS = "ACCESS_KEY ACCESS_SECRET CONSUMER_KEY CONSUMER_SECRET".split()
for key in KEYS:
    print(f"{key} in os.environ: {key in os.environ}")
    print(f"os.environ[{key}] is truthy: {bool(os.environ[key])}")
```
```
ACCESS_KEY in os.environ: True
os.environ[ACCESS_KEY] is truthy: False
ACCESS_SECRET in os.environ: True
os.environ[ACCESS_SECRET] is truthy: False
CONSUMER_KEY in os.environ: True
os.environ[CONSUMER_KEY] is truthy: False
CONSUMER_SECRET in os.environ: True
os.environ[CONSUMER_SECRET] is truthy: False
```

**Comment by rohan472000** [comment]
I had given the values also, but still i updated it now.

**Comment by cclauss** [comment]
```
Run python add_tweets_1.py
  python add_tweets_1.py
  python add_sentiment_to_tweets_2.py
  shell: /usr/bin/bash -e {0}
  env:
    ACCESS_KEY: 
    ACCESS_SECRET: 
    CONSUMER_KEY: 
    CONSUMER_SECRET: 
```

**Comment by rohan472000** [comment]
Why it is not fetching , i have saved those key values in there.

**Comment by cclauss** [comment]
I cannot say but I can tell you that this works perfectly four times every month:
https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/cron_watcher.yml#L29-L35

**Comment by cclauss** [comment]
Oh.  Secrets are not passed to forks.  This means that when I am working on a pull request, I will never get the secrets but once those changes are merged into your `main` branch, secrets should be available when the GitHub Action is run again.

**Comment by Diegomangasco** [comment]
How can we provide secrets to GitHub actions?

**Comment by cclauss** [comment]
This works perfectly four times every month:
https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/cron_watcher.yml#L29-L35

**Comment by rohan472000** [comment]
> Oh. Secrets are not passed to forks. This means that when I am working on a pull request, I will never get the secrets but once those changes are merged into your `main` branch, secrets should be available when the GitHub Action is run again.

ohh..that I didn't knew before.

**Comment by rohan472000** [comment]
@cclauss, should I merge that draft PR to check if it is fetching correctly or not, or you are still doing something on it?

**Comment by rohan472000** [comment]
> Did you setup your secrets as in
> 
> * https://medium.datadriveninvestor.com/accessing-github-secrets-in-python-d3e758d8089b
> 
> See #3
> 
> Given that the following is a Python syntax error, I would remove it.
> 
> ```
> >>> access_key = ${{ secrets.ACCESS_KEY }}
>   File "<stdin>", line 1
>     access_key = ${{ secrets.ACCESS_KEY }}
>                  ^
> SyntaxError: invalid syntax
> ```
> 
> https://github.com/rohan472000/twitter-recommender-sentiment-analysis/blob/main/add_tweets_1.py#LL7-L10C82

@Diegomangasco see the first link

**Comment by rohan472000** [comment]
@cclauss , is secret values should be kept under quotes to make it string? as in error it is showing that expecting string or byte.

**Comment by cclauss** [comment]
Merge #9 and that error will go away.

Then we need to think about #10

**Comment by cclauss** [comment]
I think this can finally be closed.

**Comment by rohan472000** [comment]
sure @cclauss ...thanks for resolving this issue and giving us new things to learn.
